### ISSUE TITLE
Does not show up on ST3 Package Control

### ISSUE THREAD

**Issue by antenando** [leandrocunha/mussum-ipsum-for-sublime-text#1]
Qualéquié rapeizis!

Your great plugin does not show up on Sublime Text 3 Package Control.

Is there any plans to porting it to ST3 as well ?

Obrigadis

**Comment by leandrocunha** [comment]
Fala ae @antenando,

Sorry but Mussum Ipsum does not have support for ST3 yet, I will do improvements to support the latest version of Sublime Text.

Thanks!
